apiVersion: v1
kind: Secret
metadata:
  name: aiven-kafka-certs
  namespace: scraping-system
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIERDCCAqygAwIBAgIUTKGO5uOdKcXfUIOzUDIzfadcf2QwDQYJKoZIhvcNAQEM
    BQAwOjE4MDYGA1UEAwwvODUyNWYxYzAtOGJhMy00OGIzLWJmOTQtMmRjZDg2ODJl
    MTY2IFByb2plY3QgQ0EwHhcNMjYwNTAyMTM1NTMyWhcNMzYwNDI5MTM1NTMyWjA6
    MTgwNgYDVQQDDC84NTI1ZjFjMC04YmEzLTQ4YjMtYmY5NC0yZGNkODY4MmUxNjYg
    UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJQd34Hf
    NinoioUC66u/LjZaV2Ov7GVI2MCr8y4N866RjPG4Em+bkF6R9d114dzbKfkrCRjF
    QWLwz1mFX+c84/A0fPTstK0BuSTYYX9IGKrde8inyhESc6CMgg2wqaH9hj5rYivw
    DtG0hXcjIMkCgQ6ffZ92VisHDntnjAs01MrsNQHDSedotUwu3yt+sW3U5qMZbyT2
    pwzqgS5W/Di4b3BrXKeJnM9nzNAPW71IG+gr8n1E4jJrgsCOd2AgLrH89VQSGqja
    hwT1l8OyOoSdRMO8VSE7Rxo+b5BkB5PNSXHWiH5q/GRQjDGZw7IMeH1mz3Z3Cd56
    ZOoWiV93iN6Gf2Yu5Cxo9/n0Tt3LlfsFMWgMt1sPMfcFYcPfssxvTp9txa7+4QKC
    /uw8FmXo49VLfqc/hDH+Ych0A+ggVp82NV+xGbCRHWCDTI7dLd3kiXjIZ9efbqTD
    QToQtIhmDFkJ6HGrDj3r6Z9UYb2iNcgDyDldrzcjAe0to78/jZ/Jz7FBqwIDAQAB
    o0IwQDAdBgNVHQ4EFgQUBJ0pbB7l+ZwsJJ+iyf2tU4OEqjQwEgYDVR0TAQH/BAgw
    BgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAD/LORkRVyBC
    GSwa/781UCwyFA7bTN+Kv3nO1YRmg+4gU0OVcwYS/wNP4UbIugRMuzmU4ChulJC2
    vIpOYJFIXIfgU2stITOUWT4uy4SbPcNYcifvY97Ois5QoE+tLHAogpmlXurocVQ+
    YywdV4V2ha9DbcOj6lBkNiAv5nT+eWpu2tVCuyMnn1ag+7vJziHPfjUg4Ee42iAj
    ZXjZXDDbCT8wVOvAFdo7YdSlSytUJkDmigClFJKVZN8pvZyy3gs4VE4Z24gVrrfu
    hu7sgaTtR2z3ScUeOpzpux1gDdNP2mdnaAol1X0cys7bsxhMNlYZPvDrBFLI5o3L
    VyLKNdCLsY20vpW23lCrMYkOL5aAWsqjg/IrkUdo90fKlHWX6OALBbYZQlvj6aMo
    Fjj/DyA0+28/0mcBseHEC2qqj1SG7tO20VfuaG3Sis1cv6zvhA326MvYizLfALPE
    EgCUUj9g5zwdwn8k/R8p31ifcRUET96aMj4o9RpQ0eTEazE6vNJKdg==
    -----END CERTIFICATE-----
